/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#9f402d",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#474747",
        "surface-container-high": "#eae8e4",
        "on-tertiary-fixed-variant": "#005144",
        "primary-fixed": "#ffdad3",
        "on-error": "#ffffff",
        "primary-container": "#e2725b",
        "surface-bright": "#fbf9f5",
        "inverse-on-surface": "#f2f0ed",
        "surface-tint": "#9f402d",
        "secondary-fixed-dim": "#c8c6c6",
        "on-background": "#1b1c1a",
        "surface-container-lowest": "#ffffff",
        "outline": "#89726d",
        "inverse-surface": "#30312e",
        "tertiary-fixed": "#7bf8dd",
        "tertiary": "#006b5b",
        "surface-container-highest": "#e4e2de",
        "secondary-container": "#e4e2e1",
        "surface-dim": "#dbdad6",
        "surface-container-low": "#f5f3ef",
        "tertiary-container": "#00a58e",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container": "#efeeea",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#00201a",
        "on-tertiary-container": "#00322a",
        "inverse-primary": "#ffb4a5",
        "tertiary-fixed-dim": "#5cdbc2",
        "surface": "#fbf9f5",
        "secondary": "#5f5e5e",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb4a5",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#802918",
        "on-primary-container": "#5a0d02",
        "on-surface": "#1b1c1a",
        "background": "#fbf9f5",
        "secondary-fixed": "#e4e2e1",
        "on-secondary-container": "#656464",
        "outline-variant": "#ddc0ba",
        "surface-variant": "#e4e2de",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#56423e",
        "on-primary-fixed": "#3e0500"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
